waypoints:
  - point:
      x: 0
      y: 0
      z: 0
  - point:
      x: -3
      y: 0
      z: 2.5
      th: 0 
  - point:
      x: -3.0
      y: 4.5
      z: 3.5
      th: 0 
  - point:
      x: 3
      y: 4
      z: 2
  - point:
      x: 3
      y: -2
      z: 2
  - point:
      x: 0
      y: 0
      z: 0